version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://scheduler:scheduler@db:5432/scheduler
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - ./:/usr/src/app
    environment:
      DATABASE_URL: postgresql://scheduler:scheduler@db:5432/scheduler
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
